import argparse
import base64
import json
import os
import re
import sys
from urllib.parse import urlparse
import requests
import json
import encrypted_video_downloader
import xml.etree.ElementTree as xml

from pywidevine.pssh import PSSH
from pywidevine.device import Device
from pywidevine.cdm import Cdm
from mpd_parser.parser import Parser
from colorama import Fore

class ComplexJsonEncoder(json.JSONEncoder):
    def default(self, o):
        if hasattr(o, 'to_json'):
            return o.to_json()
        return json.JSONEncoder.default(self, o)


class LicenseChallenge():
    def __init__(self, otp: str, playback_info: str, href: str, tech: str, license_request: str):
        self.otp = otp
        self.playback_info = playback_info
        self.href = href
        self.tech = tech
        self.license_request = license_request

    def to_json(self):
        resp = {}

        if self.otp != '':
            resp['otp'] = self.otp
        if self.playback_info != '':
            resp['playbackInfo'] = self.playback_info
        if self.href != '':
            resp['href'] = self.href
        if self.tech != '':
            resp['tech'] = self.tech
        if self.license_request != '':
            resp['licenseRequest'] = self.license_request
        return resp


def get_video_id(token: str):
    playback_info = json.loads(base64.b64decode(token))['playbackInfo']
    return json.loads(base64.b64decode(playback_info))['videoId']


def get_video_reference(token: str):
    return json.loads(base64.b64decode(token))['href']


def get_mpd(video_id: str) -> str:
    headers = {
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36',
        'origin': 'https://player.vdocipher.com/',
        'referer': 'https://player.vdocipher.com/',
        'accept': 'application/json'
    }
    url = 'https://dev.vdocipher.com/api/meta/' + video_id
    req = None
    try:
        req = requests.get(url, headers=headers)
        resp = req.json()
        return resp['dash']['manifest']

    except:  # pylint:disable=bare-except # Catch all in case a 200 doesn't contain the license
        print("Failed getting the MPD:\n", req.text)


def get_pssh(mpd: str, user_id):
    req = None
    try:
        req = requests.get(mpd)
        open(f'./downloads/vdocipher/{user_id}/Temp/stream.mpd', 'wb').write(req.content)
        return re.search('<cenc:pssh>(.*)</cenc:pssh>', req.text).group(1)
    except:  # pylint:disable=bare-except # Catch all in case a 200 doesn't contain the license
        print("Failed getting the PSSH:\n", req.text)

def get_license_response(license_challenge: str, mpd: str, video_reference: str):
    origin_url = urlparse(mpd)
    headers = {
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
        # 'origin': f'{origin_url.scheme}://{origin_url.hostname}/',
        # 'referer': f'{origin_url.scheme}://{origin_url.hostname}/',
        'origin': 'https://player.vdocipher.com',
        'referer': 'https://player.vdocipher.com/',
        'content-type': 'application/json',
        'vdo-ref': video_reference
    }
    req = None
    try:
        req = requests.post(
            'https://license.vdocipher.com/auth',
            json={'token': license_challenge},
            headers=headers
        )
        resp = req.json()
        return resp['license']
    except:  # pylint:disable=bare-except # Catch all in case a 200 doesn't contain the license
        print("Failed getting license response:\n", req.text)


def setup_license_challenge(token: str, challenge: bytes):
    decoded_token = json.loads(base64.b64decode(token))
    otp = decoded_token['otp']
    playback_info = decoded_token['playbackInfo']
    href = decoded_token['href']
    tech = decoded_token['tech']
    challenge = base64.b64encode(challenge).decode('UTF-8')

    license_challenge = LicenseChallenge(
        otp,
        playback_info,
        href,
        tech,
        challenge
    )

    raw_license_resp = json.dumps(
        license_challenge.to_json(),
        cls=ComplexJsonEncoder
    )

    return base64.b64encode(raw_license_resp.encode('UTF-8')).decode('UTF-8')


def create_argument_parser():
    parser = argparse.ArgumentParser(description='Vdocipher downloader')

    parser.add_argument(
        '--wvd',
        help='The file path to the WVD file generated by pywidevine'
    )

    parser.add_argument(
        '--token',
        help='The auth token retrieved from the Vdocipher request'
    )

    args = parser.parse_args()

    if not args.wvd or not args.token:
        parser.print_help()
    return args

def get_key_kid(user_id):
    j_file = '{ "audio":"", "video":"" }'
    data = json.loads(j_file)

    type = []
    kid = []

    def kid_maker(kid):
        temp = ""
        for i in kid:
            if i != "-":
                temp += i
        return temp

    # Function to parse XML and print attributes and their values
    def get_xml_attributes(xml_file):
        # Parse the XML file
        tree = xml.parse(xml_file)
        root = tree.getroot()

        # Recursive function to process each element
        def process_element(element):
            # Print element's attributes (if any)
            if element.attrib:
                for attr, value in element.attrib.items():
                    if attr == "{urn:mpeg:cenc:2013}default_KID" or attr == "contentType":
                        # print(f" - Attribute: {attr}, Value: {value}")
                        if value == "video" or value == "audio":
                            type.append(value)
                        if value != "video" and value != "audio":
                            kid.append(value)

            # Recursively process child elements
            for child in element:
                process_element(child)

        # Start processing from the root element
        process_element(root)

    # Example usage
    xml_file = f'./downloads/vdocipher/{user_id}/Temp/stream.mpd'  # Path to your XML file
    get_xml_attributes(xml_file)
    for i in range(0, 2):
        if type[i] == 'video':
            kid_final = kid_maker(kid[type.index('video')])
            data['video'] = kid_final
            j_file = json.dumps(data)
        else:
            kid_final = kid_maker(kid[type.index('audio')])
            data['audio'] = kid_final
            j_file = json.dumps(data)

    json_file = open(f"./downloads/vdocipher/{user_id}/Temp/kid.json", "w")
    json_file.write(j_file)
    json_file.close()

def main(wvd:str, token:str, user_id):

    wvd = wvd
    token = token
    operation = "Done"

    video_ref = get_video_reference(token)
    video_id = get_video_id(token)
    mpd = get_mpd(video_id)
    pssh = get_pssh(mpd, user_id)

    device = Device.load(wvd)
    cdm = Cdm.from_device(device)
    session_id = cdm.open()
    cdm.set_service_certificate(session_id, cdm.common_privacy_cert)
    challenge = cdm.get_license_challenge(
        session_id,
        PSSH(pssh),
        privacy_mode=True
    )

    license_challenge = setup_license_challenge(token, challenge)
    license_response = get_license_response(license_challenge, mpd, video_ref)

    cdm.parse_license(session_id, license_response)

    terminal_size = os.get_terminal_size().columns
    print('*' * terminal_size)
    get_key_kid(user_id)
    print('*' * terminal_size)

    kid_file = open(f"./downloads/vdocipher/{user_id}/Temp/kid.json", 'r')
    kid_json = kid_file.read()
    load_kid = json.loads(kid_json)
    kid_file.close()

    keys_json = '{"audio_key":"", "video_key":""}'
    print()
    for key in cdm.get_keys(session_id):
        if key.type == 'CONTENT':
            operation = "Done"
            for i in range(0,2):
                if str(key.kid.hex) == load_kid['audio']:
                    data = json.loads(keys_json)
                    data['audio_key'] = key.kid.hex + ":" + key.key.hex()
                    keys_json = json.dumps(data)
                if str(key.kid.hex) == load_kid['video']:
                    data = json.loads(keys_json)
                    data['video_key'] = key.kid.hex + ":" + key.key.hex()
                    keys_json = json.dumps(data)
        else:
            operation = "Error"

    print()
    mpd_link_file = open(f"./downloads/vdocipher/{user_id}/Temp/mpd_url.txt", "w")
    mpd_link_file.write(mpd)
    mpd_link_file.close()
    print('*' * terminal_size)
    print()
    keys = json.loads(keys_json)
    print(Fore.LIGHTYELLOW_EX + "For Decrypt Audio File")
    print(Fore.BLUE + "[KEY] " + keys['audio_key'])
    print()
    print(Fore.LIGHTYELLOW_EX + "For Decrypt VIdeo File")
    print(Fore.BLUE + "[KEY] " + keys['video_key'])
    print(Fore.LIGHTGREEN_EX)
    print('*' * terminal_size)
    keys_file = open(f'./downloads/vdocipher/{user_id}/Temp/keys.json', 'w')
    keys_file.write(keys_json)
    keys_file.close()
    cdm.close(session_id)
    print()
    if operation == "Done":
        return "Done", mpd
    else:
        return "Error", mpd